name: Generate Documentation

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |

          pip install -r requirements.txt

      - name: Run main script
        run: |
          cd docs/maker_documentation
          python main.py

      - name: Set up Git config
        run: |
          git config --global user.email "author_email"
          git config --global user.name "author_name"

      - name: Commit and push changes
        run: |
          
          #aggiorna file requirements.txt
          git add requirements.txt
          
          cd docs

          # Aggiungi i file di documentazione
          git add docs/md_docs/software-list.md || echo "No software-list.md to add"
          git add docs/md_docs/soup-list.md || echo "No soup-list.md to add"
          git add docs/md_docs/error_report.txt || echo  "No error-report.txt to add"

          # Aggiungi il file previous_software_list.json dalla cartella maker_documentation
          git add docs/maker_documentation/previous_software_list.json || echo "No previous_software_list.json to add"

          # Esegui il commit e push delle modifiche
          git commit -m 'Update documentation files and add requirements.txt' || echo "No changes to commit"
          git push origin HEAD:${{ github.head_ref }} --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
